### PR TITLE
[DASH][CRM] Extend the CRM YANG model with DASH attributes.

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
#### Why I did it
Extend the CRM YANG model with DASH attributes.
#### How I did it
Add new attributes to the existing CRM YANG model.
Implement tests for DASH CRM attributes.
#### How to verify it
Build sonic_yang_models packages. The tests will be run automatically.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@oleksandrivantsiv One comment outside this PR is we need to have sample_config_db.json for DPU as well so we can create a sample config file where we can add all possible sample configurations

**Review by dgsudharsan — COMMENTED** [review]
Can you please update Configuration.md with the list for DPU? https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md#crm

**Review by dgsudharsan — CHANGES_REQUESTED** [review]
Please update configuration.md

**Comment by oleksandrivantsiv** [comment]
> Please update configuration.md

Done

**Review by dgsudharsan — APPROVED** [review]

**Pull request closed without merging**
